/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreatePhotoResponse,
  CreatePromptResponse
} from '../adventSphereAPI.schemas';


export const getPostAiCreatePhotoResponseMock = (overrideResponse: Partial< CreatePhotoResponse > = {}): CreatePhotoResponse => ({imageData: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getPostAiCreatePromptResponseMock = (overrideResponse: Partial< CreatePromptResponse > = {}): CreatePromptResponse => ({prompt: faker.string.alpha({length: {min: 10, max: 20}}), feedback: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getPostAiCreatePhotoMockHandler = (overrideResponse?: CreatePhotoResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreatePhotoResponse> | CreatePhotoResponse), options?: RequestHandlerOptions) => {
  return http.post('*/ai/createPhoto', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostAiCreatePhotoResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostAiCreatePromptMockHandler = (overrideResponse?: CreatePromptResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreatePromptResponse> | CreatePromptResponse), options?: RequestHandlerOptions) => {
  return http.post('*/ai/createPrompt', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostAiCreatePromptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAiMock = () => [
  getPostAiCreatePhotoMockHandler(),
  getPostAiCreatePromptMockHandler()
]
