/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
  CreateRoom,
  CreateRoomResponse,
  Room,
  UpdateRoom,
} from "../adventSphereAPI.schemas";

/**
 * 新しいルームを作成します。
 * @summary ルームの作成
 */
export const postRooms = <TData = AxiosResponse<CreateRoomResponse>>(
  createRoom: CreateRoom,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/rooms`, createRoom, options);
};
/**
 * ルームIDを指定してルーム情報を取得します。
 * @summary ルーム情報の取得
 */
export const getRoomsId = <TData = AxiosResponse<Room>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/rooms/${id}`, options);
};
/**
 * ルームIDを指定してルームを削除します。
 * @summary ルームの削除
 */
export const deleteRoomsId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/rooms/${id}`, options);
};
/**
 * ルームIDを指定してルーム情報を更新します。
 * @summary ルーム情報の更新
 */
export const patchRoomsId = <TData = AxiosResponse<Room>>(
  id: string,
  updateRoom: UpdateRoom,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(`/rooms/${id}`, updateRoom, options);
};
export type PostRoomsResult = AxiosResponse<CreateRoomResponse>;
export type GetRoomsIdResult = AxiosResponse<Room>;
export type DeleteRoomsIdResult = AxiosResponse<void>;
export type PatchRoomsIdResult = AxiosResponse<Room>;
