/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type { CreateRoomResponse, Room } from "../adventSphereAPI.schemas";

export const getPostRoomsResponseMock = (
  overrideResponse: Partial<CreateRoomResponse> = {},
): CreateRoomResponse => ({
  editId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetRoomsIdResponseMock = (): Room => ({
  ...{
    ownerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    itemGetTime: faker.helpers.arrayElement([
      faker.date.past().toISOString().split("T")[0],
      undefined,
    ]),
    password: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    isAnonymous: faker.datatype.boolean(),
    startAt: faker.date.past().toISOString().split("T")[0],
  },
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.date.past().toISOString().split("T")[0],
    generateCount: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    editId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
});

export const getPatchRoomsIdResponseMock = (): Room => ({
  ...{
    ownerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    itemGetTime: faker.helpers.arrayElement([
      faker.date.past().toISOString().split("T")[0],
      undefined,
    ]),
    password: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    isAnonymous: faker.datatype.boolean(),
    startAt: faker.date.past().toISOString().split("T")[0],
  },
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.date.past().toISOString().split("T")[0],
    generateCount: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    editId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
});

export const getPostRoomsMockHandler = (
  overrideResponse?:
    | CreateRoomResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreateRoomResponse> | CreateRoomResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/rooms",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostRoomsResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetRoomsIdMockHandler = (
  overrideResponse?:
    | Room
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Room> | Room),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/rooms/:id",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRoomsIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getDeleteRoomsIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/rooms/:id",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getPatchRoomsIdMockHandler = (
  overrideResponse?:
    | Room
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<Room> | Room),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/rooms/:id",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPatchRoomsIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getRoomMock = () => [
  getPostRoomsMockHandler(),
  getGetRoomsIdMockHandler(),
  getDeleteRoomsIdMockHandler(),
  getPatchRoomsIdMockHandler(),
];
