/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
  CreateItem,
  CreateItemResponse,
  Item,
  UpdateItem,
} from "../adventSphereAPI.schemas";

/**
 * すべてのアイテムを取得します。
 * @summary アイテム一覧の取得
 */
export const getItems = <TData = AxiosResponse<Item[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/items`, options);
};
/**
 * 新しいアイテムを作成します。
 * @summary アイテムの作成
 */
export const postItems = <TData = AxiosResponse<CreateItemResponse>>(
  createItem: CreateItem,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formData = new FormData();
  formData.append(`name`, createItem.name);
  formData.append(`description`, createItem.description);
  formData.append(`type`, createItem.type);
  formData.append(`objectFile`, createItem.objectFile);

  return axios.default.post(`/items`, formData, options);
};
/**
 * アイテムIDを指定してアイテムを取得します。
 * @summary アイテムの取得
 */
export const getItemsId = <TData = AxiosResponse<Item>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/items/${id}`, options);
};
/**
 * アイテムIDを指定してアイテムを削除します。
 * @summary アイテムの削除
 */
export const deleteItemsId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/items/${id}`, options);
};
/**
 * アイテムIDを指定してアイテム情報を更新します。
 * @summary アイテムの更新
 */
export const patchItemsId = <TData = AxiosResponse<Item>>(
  id: string,
  updateItem: UpdateItem,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formData = new FormData();
  if (updateItem.name !== undefined) {
    formData.append(`name`, updateItem.name);
  }
  if (updateItem.description !== undefined) {
    formData.append(`description`, updateItem.description);
  }
  if (updateItem.type !== undefined) {
    formData.append(`type`, updateItem.type);
  }
  if (updateItem.objectFile !== undefined) {
    formData.append(`objectFile`, updateItem.objectFile);
  }

  return axios.default.patch(`/items/${id}`, formData, options);
};
export type GetItemsResult = AxiosResponse<Item[]>;
export type PostItemsResult = AxiosResponse<CreateItemResponse>;
export type GetItemsIdResult = AxiosResponse<Item>;
export type DeleteItemsIdResult = AxiosResponse<void>;
export type PatchItemsIdResult = AxiosResponse<Item>;
