/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'

const R3dSampleLazyRouteImport = createFileRoute('/3d-sample')()
const RoomIdIndexLazyRouteImport = createFileRoute('/$roomId/')()
const DebugAiLazyRouteImport = createFileRoute('/debug/ai')()
const RoomIdEditIdLazyRouteImport = createFileRoute('/$roomId/$editId')()

const R3dSampleLazyRoute = R3dSampleLazyRouteImport.update({
  id: '/3d-sample',
  path: '/3d-sample',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/3d-sample.lazy').then((d) => d.Route))
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdIndexLazyRoute = RoomIdIndexLazyRouteImport.update({
  id: '/$roomId/',
  path: '/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$roomId/index.lazy').then((d) => d.Route))
const DebugAiLazyRoute = DebugAiLazyRouteImport.update({
  id: '/debug/ai',
  path: '/debug/ai',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/debug/ai.lazy').then((d) => d.Route))
const RoomIdEditIdLazyRoute = RoomIdEditIdLazyRouteImport.update({
  id: '/$roomId/$editId',
  path: '/$roomId/$editId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$roomId/$editId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
  '/$roomId/$editId': typeof RoomIdEditIdLazyRoute
  '/debug/ai': typeof DebugAiLazyRoute
  '/$roomId': typeof RoomIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
  '/$roomId/$editId': typeof RoomIdEditIdLazyRoute
  '/debug/ai': typeof DebugAiLazyRoute
  '/$roomId': typeof RoomIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
  '/$roomId/$editId': typeof RoomIdEditIdLazyRoute
  '/debug/ai': typeof DebugAiLazyRoute
  '/$roomId/': typeof RoomIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/3d-sample'
    | '/$roomId/$editId'
    | '/debug/ai'
    | '/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/3d-sample'
    | '/$roomId/$editId'
    | '/debug/ai'
    | '/$roomId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/3d-sample'
    | '/$roomId/$editId'
    | '/debug/ai'
    | '/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  R3dSampleLazyRoute: typeof R3dSampleLazyRoute
  RoomIdEditIdLazyRoute: typeof RoomIdEditIdLazyRoute
  DebugAiLazyRoute: typeof DebugAiLazyRoute
  RoomIdIndexLazyRoute: typeof RoomIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/3d-sample': {
      id: '/3d-sample'
      path: '/3d-sample'
      fullPath: '/3d-sample'
      preLoaderRoute: typeof R3dSampleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId/': {
      id: '/$roomId/'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/ai': {
      id: '/debug/ai'
      path: '/debug/ai'
      fullPath: '/debug/ai'
      preLoaderRoute: typeof DebugAiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId/$editId': {
      id: '/$roomId/$editId'
      path: '/$roomId/$editId'
      fullPath: '/$roomId/$editId'
      preLoaderRoute: typeof RoomIdEditIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  R3dSampleLazyRoute: R3dSampleLazyRoute,
  RoomIdEditIdLazyRoute: RoomIdEditIdLazyRoute,
  DebugAiLazyRoute: DebugAiLazyRoute,
  RoomIdIndexLazyRoute: RoomIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
