/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'

const R3dSampleLazyRouteImport = createFileRoute('/3d-sample')()

const R3dSampleLazyRoute = R3dSampleLazyRouteImport.update({
  id: '/3d-sample',
  path: '/3d-sample',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/3d-sample.lazy').then((d) => d.Route))
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/3d-sample': typeof R3dSampleLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/3d-sample'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/3d-sample'
  id: '__root__' | '/' | '/new' | '/3d-sample'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  R3dSampleLazyRoute: typeof R3dSampleLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/3d-sample': {
      id: '/3d-sample'
      path: '/3d-sample'
      fullPath: '/3d-sample'
      preLoaderRoute: typeof R3dSampleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  R3dSampleLazyRoute: R3dSampleLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
