/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CalendarItem,
  CalendarItemWithItem,
  CreateCalendarItemResponse
} from '../adventSphereAPI.schemas';


export const getGetCalendarItemsRoomIdCalendarItemsResponseMock = (): CalendarItemWithItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({...{id: faker.string.alpha({length: {min: 10, max: 20}}), userId: faker.string.alpha({length: {min: 10, max: 20}}), userName: faker.string.alpha({length: {min: 10, max: 20}}), roomId: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, openDate: `${faker.date.past().toISOString().split('.')[0]}Z`, position: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), rotation: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), isOpened: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), itemId: faker.string.alpha({length: {min: 10, max: 20}}), imageId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])},...{item: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})}},})))

export const getPostCalendarItemsRoomIdCalendarItemsResponseMock = (overrideResponse: Partial< CreateCalendarItemResponse > = {}): CreateCalendarItemResponse => ({id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getPatchCalendarItemsRoomIdCalendarItemsIdResponseMock = (overrideResponse: Partial< CalendarItem > = {}): CalendarItem => ({id: faker.string.alpha({length: {min: 10, max: 20}}), userId: faker.string.alpha({length: {min: 10, max: 20}}), userName: faker.string.alpha({length: {min: 10, max: 20}}), roomId: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, openDate: `${faker.date.past().toISOString().split('.')[0]}Z`, position: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), rotation: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), isOpened: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), itemId: faker.string.alpha({length: {min: 10, max: 20}}), imageId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getGetCalendarItemsRoomIdCalendarItemsInventoryResponseMock = (): CalendarItemWithItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({...{id: faker.string.alpha({length: {min: 10, max: 20}}), userId: faker.string.alpha({length: {min: 10, max: 20}}), userName: faker.string.alpha({length: {min: 10, max: 20}}), roomId: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, openDate: `${faker.date.past().toISOString().split('.')[0]}Z`, position: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), rotation: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), isOpened: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), itemId: faker.string.alpha({length: {min: 10, max: 20}}), imageId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])},...{item: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}})}},})))

export const getGetCalendarItemsRoomIdCalendarItemsRoomResponseMock = (): CalendarItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), userId: faker.string.alpha({length: {min: 10, max: 20}}), userName: faker.string.alpha({length: {min: 10, max: 20}}), roomId: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, openDate: `${faker.date.past().toISOString().split('.')[0]}Z`, position: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), rotation: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), undefined]), isOpened: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), itemId: faker.string.alpha({length: {min: 10, max: 20}}), imageId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})))


export const getGetCalendarItemsRoomIdCalendarItemsMockHandler = (overrideResponse?: CalendarItemWithItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CalendarItemWithItem[]> | CalendarItemWithItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/calendarItems/:roomId/calendarItems', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCalendarItemsRoomIdCalendarItemsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostCalendarItemsRoomIdCalendarItemsMockHandler = (overrideResponse?: CreateCalendarItemResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateCalendarItemResponse> | CreateCalendarItemResponse), options?: RequestHandlerOptions) => {
  return http.post('*/calendarItems/:roomId/calendarItems', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostCalendarItemsRoomIdCalendarItemsResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteCalendarItemsRoomIdCalendarItemsIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/calendarItems/:roomId/calendarItems/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getPatchCalendarItemsRoomIdCalendarItemsIdMockHandler = (overrideResponse?: CalendarItem | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<CalendarItem> | CalendarItem), options?: RequestHandlerOptions) => {
  return http.patch('*/calendarItems/:roomId/calendarItems/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPatchCalendarItemsRoomIdCalendarItemsIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetCalendarItemsRoomIdCalendarItemsInventoryMockHandler = (overrideResponse?: CalendarItemWithItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CalendarItemWithItem[]> | CalendarItemWithItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/calendarItems/:roomId/calendarItems/inventory', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCalendarItemsRoomIdCalendarItemsInventoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetCalendarItemsRoomIdCalendarItemsRoomMockHandler = (overrideResponse?: CalendarItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CalendarItem[]> | CalendarItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/calendarItems/:roomId/calendarItems/room', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCalendarItemsRoomIdCalendarItemsRoomResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getCalendarItemsMock = () => [
  getGetCalendarItemsRoomIdCalendarItemsMockHandler(),
  getPostCalendarItemsRoomIdCalendarItemsMockHandler(),
  getDeleteCalendarItemsRoomIdCalendarItemsIdMockHandler(),
  getPatchCalendarItemsRoomIdCalendarItemsIdMockHandler(),
  getGetCalendarItemsRoomIdCalendarItemsInventoryMockHandler(),
  getGetCalendarItemsRoomIdCalendarItemsRoomMockHandler()
]
