/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
  CalendarItem,
  CreateCalendarItemRequest,
  CreateCalendarItemResponse,
  DeleteCalendarItemsRoomIdCalendarItemsIdBody,
  PatchCalendarItemRequest,
} from "../adventSphereAPI.schemas";

/**
 * すべてのカレンダーアイテムを取得します。
 * @summary カレンダーアイテム一覧の取得
 */
export const getCalendarItemsRoomIdCalendarItems = <
  TData = AxiosResponse<CalendarItem[]>,
>(
  roomId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/calendarItems/${roomId}/calendarItems`, options);
};
/**
 * 新しいカレンダーアイテムを作成します。
 * @summary カレンダーアイテムの作成
 */
export const postCalendarItemsRoomIdCalendarItems = <
  TData = AxiosResponse<CreateCalendarItemResponse>,
>(
  roomId: string,
  createCalendarItemRequest: CreateCalendarItemRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `/calendarItems/${roomId}/calendarItems`,
    createCalendarItemRequest,
    options,
  );
};
/**
 * 指定したIDのカレンダーアイテムを削除します。
 * @summary カレンダーアイテムの削除
 */
export const deleteCalendarItemsRoomIdCalendarItemsId = <
  TData = AxiosResponse<void>,
>(
  roomId: string,
  id: string,
  deleteCalendarItemsRoomIdCalendarItemsIdBody: DeleteCalendarItemsRoomIdCalendarItemsIdBody,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/calendarItems/${roomId}/calendarItems/${id}`, {
    data: deleteCalendarItemsRoomIdCalendarItemsIdBody,
    ...options,
  });
};
/**
 * 指定したIDのカレンダーアイテム情報を更新します。
 * @summary カレンダーアイテムの更新
 */
export const patchCalendarItemsRoomIdCalendarItemsId = <
  TData = AxiosResponse<CalendarItem>,
>(
  roomId: string,
  id: string,
  patchCalendarItemRequest: PatchCalendarItemRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `/calendarItems/${roomId}/calendarItems/${id}`,
    patchCalendarItemRequest,
    options,
  );
};
export type GetCalendarItemsRoomIdCalendarItemsResult = AxiosResponse<
  CalendarItem[]
>;
export type PostCalendarItemsRoomIdCalendarItemsResult =
  AxiosResponse<CreateCalendarItemResponse>;
export type DeleteCalendarItemsRoomIdCalendarItemsIdResult =
  AxiosResponse<void>;
export type PatchCalendarItemsRoomIdCalendarItemsIdResult =
  AxiosResponse<CalendarItem>;
