/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CalendarItem,
  CalendarItemWithItem,
  CreateCalendarItemRequest,
  CreateCalendarItemResponse,
  DeleteCalendarItemsRoomIdCalendarItemsIdBody,
  PatchCalendarItemRequest
} from '../adventSphereAPI.schemas';

import { axiosInstance } from '../../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * すべてのカレンダーアイテムを取得します。
 * @summary カレンダーアイテム一覧の取得
 */
export const getCalendarItemsRoomIdCalendarItems = (
    roomId: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<CalendarItemWithItem[]>(
      {url: `/calendarItems/${roomId}/calendarItems`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCalendarItemsRoomIdCalendarItemsQueryKey = (roomId?: string,) => {
    return [
    `/calendarItems/${roomId}/calendarItems`
    ] as const;
    }

    
export const getGetCalendarItemsRoomIdCalendarItemsQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError = unknown>(roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarItemsRoomIdCalendarItemsQueryKey(roomId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>> = ({ signal }) => getCalendarItemsRoomIdCalendarItems(roomId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(roomId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalendarItemsRoomIdCalendarItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>>
export type GetCalendarItemsRoomIdCalendarItemsQueryError = unknown


export function useGetCalendarItemsRoomIdCalendarItems<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError = unknown>(
 roomId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItems<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItems<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary カレンダーアイテム一覧の取得
 */

export function useGetCalendarItemsRoomIdCalendarItems<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalendarItemsRoomIdCalendarItemsQueryOptions(roomId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 新しいカレンダーアイテムを作成します。
 * @summary カレンダーアイテムの作成
 */
export const postCalendarItemsRoomIdCalendarItems = (
    roomId: string,
    createCalendarItemRequest: CreateCalendarItemRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<CreateCalendarItemResponse>(
      {url: `/calendarItems/${roomId}/calendarItems`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCalendarItemRequest, signal
    },
      options);
    }
  


export const getPostCalendarItemsRoomIdCalendarItemsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>, TError,{roomId: string;data: CreateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>, TError,{roomId: string;data: CreateCalendarItemRequest}, TContext> => {

const mutationKey = ['postCalendarItemsRoomIdCalendarItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>, {roomId: string;data: CreateCalendarItemRequest}> = (props) => {
          const {roomId,data} = props ?? {};

          return  postCalendarItemsRoomIdCalendarItems(roomId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCalendarItemsRoomIdCalendarItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>>
    export type PostCalendarItemsRoomIdCalendarItemsMutationBody = CreateCalendarItemRequest
    export type PostCalendarItemsRoomIdCalendarItemsMutationError = void

    /**
 * @summary カレンダーアイテムの作成
 */
export const usePostCalendarItemsRoomIdCalendarItems = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>, TError,{roomId: string;data: CreateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCalendarItemsRoomIdCalendarItems>>,
        TError,
        {roomId: string;data: CreateCalendarItemRequest},
        TContext
      > => {

      const mutationOptions = getPostCalendarItemsRoomIdCalendarItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 指定したIDのカレンダーアイテムを削除します。
 * @summary カレンダーアイテムの削除
 */
export const deleteCalendarItemsRoomIdCalendarItemsId = (
    roomId: string,
    id: string,
    deleteCalendarItemsRoomIdCalendarItemsIdBody: DeleteCalendarItemsRoomIdCalendarItemsIdBody,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<void>(
      {url: `/calendarItems/${roomId}/calendarItems/${id}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteCalendarItemsRoomIdCalendarItemsIdBody
    },
      options);
    }
  


export const getDeleteCalendarItemsRoomIdCalendarItemsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: DeleteCalendarItemsRoomIdCalendarItemsIdBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: DeleteCalendarItemsRoomIdCalendarItemsIdBody}, TContext> => {

const mutationKey = ['deleteCalendarItemsRoomIdCalendarItemsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>, {roomId: string;id: string;data: DeleteCalendarItemsRoomIdCalendarItemsIdBody}> = (props) => {
          const {roomId,id,data} = props ?? {};

          return  deleteCalendarItemsRoomIdCalendarItemsId(roomId,id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCalendarItemsRoomIdCalendarItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>>
    export type DeleteCalendarItemsRoomIdCalendarItemsIdMutationBody = DeleteCalendarItemsRoomIdCalendarItemsIdBody
    export type DeleteCalendarItemsRoomIdCalendarItemsIdMutationError = unknown

    /**
 * @summary カレンダーアイテムの削除
 */
export const useDeleteCalendarItemsRoomIdCalendarItemsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: DeleteCalendarItemsRoomIdCalendarItemsIdBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCalendarItemsRoomIdCalendarItemsId>>,
        TError,
        {roomId: string;id: string;data: DeleteCalendarItemsRoomIdCalendarItemsIdBody},
        TContext
      > => {

      const mutationOptions = getDeleteCalendarItemsRoomIdCalendarItemsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 指定したIDのカレンダーアイテム情報を更新します。
 * @summary カレンダーアイテムの更新
 */
export const patchCalendarItemsRoomIdCalendarItemsId = (
    roomId: string,
    id: string,
    patchCalendarItemRequest: PatchCalendarItemRequest,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<CalendarItem>(
      {url: `/calendarItems/${roomId}/calendarItems/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchCalendarItemRequest
    },
      options);
    }
  


export const getPatchCalendarItemsRoomIdCalendarItemsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: PatchCalendarItemRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: PatchCalendarItemRequest}, TContext> => {

const mutationKey = ['patchCalendarItemsRoomIdCalendarItemsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>, {roomId: string;id: string;data: PatchCalendarItemRequest}> = (props) => {
          const {roomId,id,data} = props ?? {};

          return  patchCalendarItemsRoomIdCalendarItemsId(roomId,id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchCalendarItemsRoomIdCalendarItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>>
    export type PatchCalendarItemsRoomIdCalendarItemsIdMutationBody = PatchCalendarItemRequest
    export type PatchCalendarItemsRoomIdCalendarItemsIdMutationError = void

    /**
 * @summary カレンダーアイテムの更新
 */
export const usePatchCalendarItemsRoomIdCalendarItemsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>, TError,{roomId: string;id: string;data: PatchCalendarItemRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchCalendarItemsRoomIdCalendarItemsId>>,
        TError,
        {roomId: string;id: string;data: PatchCalendarItemRequest},
        TContext
      > => {

      const mutationOptions = getPatchCalendarItemsRoomIdCalendarItemsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * インベントリーに入っているアイテムを取得します。
 * @summary インベントリーに入っているアイテムの取得
 */
export const getCalendarItemsRoomIdCalendarItemsInventory = (
    roomId: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<CalendarItemWithItem[]>(
      {url: `/calendarItems/${roomId}/calendarItems/inventory`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCalendarItemsRoomIdCalendarItemsInventoryQueryKey = (roomId?: string,) => {
    return [
    `/calendarItems/${roomId}/calendarItems/inventory`
    ] as const;
    }

    
export const getGetCalendarItemsRoomIdCalendarItemsInventoryQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError = unknown>(roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarItemsRoomIdCalendarItemsInventoryQueryKey(roomId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>> = ({ signal }) => getCalendarItemsRoomIdCalendarItemsInventory(roomId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(roomId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalendarItemsRoomIdCalendarItemsInventoryQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>>
export type GetCalendarItemsRoomIdCalendarItemsInventoryQueryError = unknown


export function useGetCalendarItemsRoomIdCalendarItemsInventory<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError = unknown>(
 roomId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItemsInventory<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItemsInventory<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary インベントリーに入っているアイテムの取得
 */

export function useGetCalendarItemsRoomIdCalendarItemsInventory<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsInventory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalendarItemsRoomIdCalendarItemsInventoryQueryOptions(roomId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 部屋に配置されているアイテムを取得します。
 * @summary 部屋に配置されているアイテムの取得
 */
export const getCalendarItemsRoomIdCalendarItemsRoom = (
    roomId: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<CalendarItem[]>(
      {url: `/calendarItems/${roomId}/calendarItems/room`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCalendarItemsRoomIdCalendarItemsRoomQueryKey = (roomId?: string,) => {
    return [
    `/calendarItems/${roomId}/calendarItems/room`
    ] as const;
    }

    
export const getGetCalendarItemsRoomIdCalendarItemsRoomQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError = unknown>(roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarItemsRoomIdCalendarItemsRoomQueryKey(roomId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>> = ({ signal }) => getCalendarItemsRoomIdCalendarItemsRoom(roomId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(roomId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalendarItemsRoomIdCalendarItemsRoomQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>>
export type GetCalendarItemsRoomIdCalendarItemsRoomQueryError = unknown


export function useGetCalendarItemsRoomIdCalendarItemsRoom<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError = unknown>(
 roomId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItemsRoom<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>,
          TError,
          Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarItemsRoomIdCalendarItemsRoom<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 部屋に配置されているアイテムの取得
 */

export function useGetCalendarItemsRoomIdCalendarItemsRoom<TData = Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarItemsRoomIdCalendarItemsRoom>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalendarItemsRoomIdCalendarItemsRoomQueryOptions(roomId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




