/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
export interface CalendarItem {
  /** カレンダーアイテムID */
  id: string;
  /** ユーザーID */
  userId: string;
  /** ルームID */
  roomId: string;
  /** 作成日時 */
  createdAt: string;
  /** 開封可能日時 */
  openDate: string;
  /** アイテムの位置情報 */
  position?: number[];
  /** アイテムの回転情報 */
  rotation?: number[];
  /** アイテムが開封されたかどうか */
  isOpened: boolean;
  /** 関連するアイテムID */
  itemId: string;
  /** 関連する画像ID */
  imageId?: string;
}

export interface CreateCalendarItemResponse {
  /** カレンダーアイテムID */
  id: string;
}

export interface CreateCalendarItem {
  /** ユーザーID */
  userId: string;
  /** ルームID */
  roomId: string;
  /** 開封可能日時 */
  openDate: string;
  /** アイテムの位置情報 */
  position?: number[];
  /** アイテムの回転情報 */
  rotation?: number[];
  /** 関連するアイテムID */
  itemId: string;
  /** 関連する画像ID */
  imageId?: string;
}

export interface CreateCalendarItemRequest {
  /** ルームの編集ID */
  editId: string;
  calendarItem: CreateCalendarItem;
}

export type PatchCalendarItemRequestCalendarItem = {
  /** ユーザーID */
  userId?: string;
  /** ルームID */
  roomId?: string;
  /** 開封可能日時 */
  openDate?: string;
  /** アイテムの位置情報 */
  position?: number[];
  /** アイテムの回転情報 */
  rotation?: number[];
  /** 関連するアイテムID */
  itemId?: string;
  /** 関連する画像ID */
  imageId?: string;
};

export interface PatchCalendarItemRequest {
  /** ルームの編集ID */
  editId: string;
  calendarItem: PatchCalendarItemRequestCalendarItem;
}

export interface User {
  /** ユーザーID */
  id: string;
  /** ユーザー作成日時のタイムスタンプ */
  createdAt: string;
  /** ユーザー名 */
  name: string;
}

export interface CreateUser {
  /** ユーザーID */
  id: string;
  /** ユーザー名 */
  name: string;
}

export interface Item {
  /** アイテムID */
  id: string;
  /** アイテム名 */
  name: string;
  /** アイテム作成日時 */
  createdAt: string;
  /** アイテムの説明 */
  description: string;
  /** アイテムの種類 */
  type: string;
}

export interface CreateItemResponse {
  /** アイテムID */
  id: string;
  /** アイテム名 */
  name: string;
}

export interface CreateItemError {
  error: string;
}

export interface CreateItem {
  /** アイテム名 */
  name: string;
  /** アイテムの説明 */
  description: string;
  /** アイテムの種類 */
  type: string;
  /** アイテムの3Dモデルファイル */
  objectFile: Blob;
  /** アイテムのサムネイル画像ファイル */
  objectThumbnail: Blob;
}

export interface UpdateItem {
  /** アイテム名 */
  name?: string;
  /** アイテムの説明 */
  description?: string;
  /** アイテムの種類 */
  type?: string;
  /** アイテムの3Dモデルファイル */
  objectFile?: Blob;
  /** アイテムのサムネイル画像ファイル */
  objectThumbnail?: Blob;
}

export interface CreateRoomResponse {
  /** ルームID */
  id: string;
  /** ルームの編集ID */
  editId: string;
}

export interface CreateRoom {
  /** オーナーのユーザーID */
  ownerId: string;
  /** アイテム取得日時 */
  itemGetTime?: string;
  /** ルームのパスワード */
  password?: string;
  /** 匿名モードかどうか */
  isAnonymous: boolean;
  /** 開始日時 */
  startAt: string;
}

export interface Room {
  /** ルームID */
  id: string;
  /** オーナーのユーザーID */
  ownerId: string;
  /** アイテム取得日時 */
  itemGetTime: string;
  /**
   * ルームのパスワード
   * @nullable
   */
  password: string | null;
  /** 匿名モードかどうか */
  isAnonymous: boolean;
  /** 開始日時 */
  startAt: string;
  /** ルーム作成日時 */
  createdAt: string;
  /** 生成回数 */
  generateCount: number;
  /** ルームの編集ID */
  editId: string;
}

export interface UpdateRoom {
  /** アイテム取得日時 */
  itemGetTime?: string;
  /** ルームのパスワード */
  password?: string;
  /** 匿名モードかどうか */
  isAnonymous?: boolean;
  /** 開始日時 */
  startAt?: string;
}

export interface CreatePhotoResponse {
  /** base64エンコードされた画像データ */
  imageData: string;
}

export interface CreatePhotoRequest {
  /** 画像生成のためのプロンプト */
  prompt: string;
}

export interface CreatePromptResponse {
  /** 生成された写真プロンプト */
  prompt: string;
}

/**
 * 発言者の役割
 */
export type CreatePromptRequestHistoryItemRole = typeof CreatePromptRequestHistoryItemRole[keyof typeof CreatePromptRequestHistoryItemRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePromptRequestHistoryItemRole = {
  user: 'user',
  model: 'model',
} as const;

export type CreatePromptRequestHistoryItem = {
  /** 発言者の役割 */
  role: CreatePromptRequestHistoryItemRole;
  /** 発言内容 */
  content: string;
};

export interface CreatePromptRequest {
  /** 写真プロンプトのテーマ */
  prompt: string;
  /** これまでの会話履歴 */
  history: CreatePromptRequestHistoryItem[];
}

export type DeleteCalendarItemsRoomIdCalendarItemsIdBody = {
  /** ルームの編集ID */
  editId: string;
};

