/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
  CreatePhotoRequest,
  CreatePhotoResponse,
} from "../adventSphereAPI.schemas";

/**
 * 新しい写真を作成します。
 * @summary 写真の作成
 */
export const postOtherCreatePhoto = <
  TData = AxiosResponse<CreatePhotoResponse>,
>(
  createPhotoRequest: CreatePhotoRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/other/createPhoto`, createPhotoRequest, options);
};
export type PostOtherCreatePhotoResult = AxiosResponse<CreatePhotoResponse>;
