/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
  CreatePhotoResponse,
  CreatePromptResponse,
} from "../adventSphereAPI.schemas";

export const getPostOtherCreatePhotoResponseMock = (
  overrideResponse: Partial<CreatePhotoResponse> = {},
): CreatePhotoResponse => ({
  imageData: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getPostOtherCreatePromptResponseMock = (
  overrideResponse: Partial<CreatePromptResponse> = {},
): CreatePromptResponse => ({
  prompt: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getPostOtherCreatePhotoMockHandler = (
  overrideResponse?:
    | CreatePhotoResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreatePhotoResponse> | CreatePhotoResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/other/createPhoto",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostOtherCreatePhotoResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostOtherCreatePromptMockHandler = (
  overrideResponse?:
    | CreatePromptResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreatePromptResponse> | CreatePromptResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/other/createPrompt",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostOtherCreatePromptResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getOtherMock = () => [
  getPostOtherCreatePhotoMockHandler(),
  getPostOtherCreatePromptMockHandler(),
];
