/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { axiosInstance } from "../../axios-instance";
import type {
  CreatePhotoRequest,
  CreatePhotoResponse,
  CreatePromptRequest,
  CreatePromptResponse,
} from "../adventSphereAPI.schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 新しい写真を作成します。
 * @summary 写真の作成
 */
export const postOtherCreatePhoto = (
  createPhotoRequest: CreatePhotoRequest,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CreatePhotoResponse>(
    {
      url: `/other/createPhoto`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPhotoRequest,
      signal,
    },
    options,
  );
};

export const getPostOtherCreatePhotoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOtherCreatePhoto>>,
    TError,
    { data: CreatePhotoRequest },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOtherCreatePhoto>>,
  TError,
  { data: CreatePhotoRequest },
  TContext
> => {
  const mutationKey = ["postOtherCreatePhoto"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOtherCreatePhoto>>,
    { data: CreatePhotoRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postOtherCreatePhoto(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOtherCreatePhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOtherCreatePhoto>>
>;
export type PostOtherCreatePhotoMutationBody = CreatePhotoRequest;
export type PostOtherCreatePhotoMutationError = unknown;

/**
 * @summary 写真の作成
 */
export const usePostOtherCreatePhoto = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOtherCreatePhoto>>,
      TError,
      { data: CreatePhotoRequest },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOtherCreatePhoto>>,
  TError,
  { data: CreatePhotoRequest },
  TContext
> => {
  const mutationOptions = getPostOtherCreatePhotoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * AIを用いて写真プロンプトを生成します。
 * @summary AIを用いて写真プロンプトを生成する
 */
export const postOtherCreatePrompt = (
  createPromptRequest: CreatePromptRequest,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CreatePromptResponse>(
    {
      url: `/other/createPrompt`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPromptRequest,
      signal,
    },
    options,
  );
};

export const getPostOtherCreatePromptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOtherCreatePrompt>>,
    TError,
    { data: CreatePromptRequest },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOtherCreatePrompt>>,
  TError,
  { data: CreatePromptRequest },
  TContext
> => {
  const mutationKey = ["postOtherCreatePrompt"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOtherCreatePrompt>>,
    { data: CreatePromptRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postOtherCreatePrompt(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOtherCreatePromptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOtherCreatePrompt>>
>;
export type PostOtherCreatePromptMutationBody = CreatePromptRequest;
export type PostOtherCreatePromptMutationError = unknown;

/**
 * @summary AIを用いて写真プロンプトを生成する
 */
export const usePostOtherCreatePrompt = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOtherCreatePrompt>>,
      TError,
      { data: CreatePromptRequest },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOtherCreatePrompt>>,
  TError,
  { data: CreatePromptRequest },
  TContext
> => {
  const mutationOptions = getPostOtherCreatePromptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
