/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type { User } from "../adventSphereAPI.schemas";

export const getGetUsersIdResponseMock = (
  overrideResponse: Partial<User> = {},
): User => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getPostUsersResponseMock = (
  overrideResponse: Partial<User> = {},
): User => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetUsersIdMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/users/:id",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetUsersIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostUsersMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/users",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostUsersResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getUserMock = () => [
  getGetUsersIdMockHandler(),
  getPostUsersMockHandler(),
];
