/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * advent-sphere API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type { CreateUser, User } from "../adventSphereAPI.schemas";

/**
 * ユーザーIDを指定してユーザー情報を取得します。
 * @summary ユーザー情報の取得
 */
export const getUsersId = <TData = AxiosResponse<User>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/users/${id}`, options);
};
/**
 * 新しいユーザーを作成します。
 * @summary ユーザーの作成
 */
export const postUsers = <TData = AxiosResponse<User>>(
  createUser: CreateUser,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/users`, createUser, options);
};
export type GetUsersIdResult = AxiosResponse<User>;
export type PostUsersResult = AxiosResponse<User>;
